name: CMake

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: build examples and tests
      run: rm -rf build || true && mkdir build && cd build && cmake .. -DLIBMBUS_BUILD_EXAMPLES=ON -DLIBMBUS_BUILD_TESTS=ON && cmake --build . -j

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: package
      run: sudo apt install socat
    - name: test
      run: sudo python3 test/slave-test.py

  debian:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: build debian package
      run: rm -rf build || true && mkdir build && cd build && cmake .. -DLIBMBUS_PACKAGE_DEB=ON && cpack .. && sudo dpkg -i *.deb && ls /usr/lib

  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build doxygen documentation
      run: sudo apt install -y doxygen
      
    - name: build doxygen documentation
      run: rm -rf build || true && mkdir build && cd build && cmake .. -DLIBMBUS_BUILD_DOCS=ON && cmake --build . --target doc

