name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./build.sh
    - name: package
      run: sudo apt install socat
    - name: test
      run: sudo python3 test/slave-test.py
